version: 2.1

jobs:
  deploy_to_github_pages:
    docker:
      - image: node:8
    steps:
      - run:
          name: Ensure environment variables are present
          command: |
            set -eu
            echo "${ALGOLIA_APP_ID}${ALGOLIA_SEARCH_ONLY_API_KEY}${ALGOLIA_ADMIN_API_KEY}${ALGOLIA_INDEX_NAME}" &> /dev/null
            echo "${GIT_AUTHOR_EMAIL}${GIT_COMMITTER_NAME}${EMAIL}" &> /dev/null
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: install node modules
          command: npm i
      - run:
          name: deploy to github pages (master branch is used for public site)
          command: npm run deploy
      - run:
          name: remove gh-pages cache before saving node_modules cache
          command: rm -rf node_modules/gh-pages/.cache
      - save_cache:
          key: v2-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  workflow:
    jobs:
      - deploy_to_github_pages:
          filters:
            branches:
              only: develop
